import type { Metadata } from "next";
import NavBar from "./components/NavBar";
import {ClerkProvider} from "@clerk/nextjs"
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body className="flex flex-col">
          <NavBar/>
          <div className="w-full mt-20">
            {children}
          </div>
        </body>
        
      </ClerkProvider>
    </html>
  );
}
